// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LH9LOGLXFlqlOlHF0JOJZjcc_1Fdong',
    appId: '1:452487146883:web:82d3d8f83f9f0367b7dab6',
    messagingSenderId: '452487146883',
    projectId: 'gazesport-b5620',
    authDomain: 'gazesport-b5620.firebaseapp.com',
    storageBucket: 'gazesport-b5620.appspot.com',
    measurementId: 'G-XTYXJEQSTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrtlyPstae_gIdifZ3fxlItMU7EH0CISM',
    appId: '1:452487146883:android:93cacd6ae899cd22b7dab6',
    messagingSenderId: '452487146883',
    projectId: 'gazesport-b5620',
    storageBucket: 'gazesport-b5620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrzRbo-rynF7RD8PMb8pWsQt0FZUKTA4',
    appId: '1:452487146883:ios:cd9960d22ffa251eb7dab6',
    messagingSenderId: '452487146883',
    projectId: 'gazesport-b5620',
    storageBucket: 'gazesport-b5620.appspot.com',
    iosClientId: '452487146883-dcc7f45sl6jl3nec8ditg88h678ssnue.apps.googleusercontent.com',
    iosBundleId: 'com.example.gazesport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIrzRbo-rynF7RD8PMb8pWsQt0FZUKTA4',
    appId: '1:452487146883:ios:cd9960d22ffa251eb7dab6',
    messagingSenderId: '452487146883',
    projectId: 'gazesport-b5620',
    storageBucket: 'gazesport-b5620.appspot.com',
    iosClientId: '452487146883-dcc7f45sl6jl3nec8ditg88h678ssnue.apps.googleusercontent.com',
    iosBundleId: 'com.example.gazesport',
  );
}
